version: '3'
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword