CREATE TYPE UpdateType AS ENUM (
  'new',
  'improvements_bugs'
);

CREATE TABLE "update" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp,
  "title" text NOT NULL,
  "cover_image" varchar(250) NOT NULL,
  "content" varchar(500) NOT NULL
);

CREATE TABLE "updatepoint" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "title" text NOT NULL,
  "content" varchar(500) NOT NULL,
  "type" UpdateType,
  "update_id" integer
);

CREATE TABLE "contributor" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "first_name" varchar(100) NOT NULL,
  "last_name" varchar(100) NOT NULL,
  "profile_picture" varchar(250),
  "role" varchar(250) NOT NULL
);

CREATE TABLE "contribution" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "updatepoint_id" integer NOT NULL,
  "contributor_id" integer NOT NULL
);

ALTER TABLE "updatepoint" ADD FOREIGN KEY ("update_id") REFERENCES "update" ("id");

ALTER TABLE "contribution" ADD FOREIGN KEY ("updatepoint_id") REFERENCES "updatepoint" ("id");

ALTER TABLE "contribution" ADD FOREIGN KEY ("contributor_id") REFERENCES "contributor" ("id");